[tool.poetry]
name = "copy safer"
version = "0.1.0"
description = ""
authors = ["kty1004 <ktyoung1004@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
